Week 4 - Spring Core Assignment
affandyfandy/java-manuella pull request #2
Opened 2024-07-02 15:50 UTC by manuellaiv

2024-07-03 04:09 UTC, irhamnaufal8 commented
## My Opinion
Overall, it's already good and well written 👍🏻. But maybe there's a couple thing that can be improved from the documentation.

#### Assignment 2
- Task 1: I think for the Constructor Injection, it's okay if we don't add the `@AutoWired` annotation.
- Already provide the Optional Task 👍🏻

#### Assignment 3
- Task 1 & 2: It might be easier to read/review if the task is provided in the MD file, so the reviewer can directly read the code or navigate to the source code. And maybe you can add the documentation of the result.
- Already provide the Optional Task 👍🏻

2024-07-05 09:11 UTC, irhamnaufal8 commented
## My Opinion for Lecture 8
The implementation already good and the tutorial of how to run the project is really helpful 👍🏻. Maybe I just want to suggest another annotation from Lombok:

- You can use `@Data` annotation to generates getters, setters, toString, equals, and hashCode methods, so you don't need `@Getter` and `@Setter`
- You can also use `@AllArgsConstructor`  to generates constructor with all arguments.

2024-07-08 06:57 UTC, helenhash requested changes
Lecture 7
Assigment 2: 
For best practice, what is DI type we should use? I dont see you mention.
Good understanding about Circular DI. need to mention that Circular DI shoud be avoided.
What is case we can skip @ComponentScan ignore?

Lecture 8:
Notice about handle exception when interact with DB
Get value from prop file by @Value

Pls see more on comment in this PR below.

2024-07-08 06:57 UTC, helenhash commented on Week 04/Lecture 07/Assignment 02/Assignment7_2/src/main/java/com/week4/Assignment7_2/service/EmployeeService.java
> +    public void setEmailService(EmailService emailService) {
Should think about which way of DI is better ?

2024-07-08 06:57 UTC, helenhash commented on Week 04/Lecture 08/Assignment 02/src/main/java/com/lecture8/EmployeeCRUD/dao/EmployeeDAO.java
> +        String sql = "SELECT * FROM employees WHERE id = ?";
Should handle exception for query

2024-07-08 06:57 UTC, helenhash commented on Week 04/Lecture 08/Assignment 02/src/main/java/com/lecture8/EmployeeCRUD/dao/EmployeeDAO.java
> +        for (Employee employee : employees) {
Should not save item inside the loop like this.

2024-07-08 06:57 UTC, helenhash commented on Week 04/Lecture 08/Assignment 03/src/main/java/com/lecture8/EmployeeCRUD/config/DataSourceConfig.java
> +        dataSourceBuilder.url(System.getenv("DB_URL"));
It's good to put url, username, pass in prop file, but it's better to use @Value to get value from prop file

2024-07-08 06:57 UTC, helenhash commented on Week 04/Lecture 08/Assignment 03/src/main/java/com/lecture8/EmployeeCRUD/controllers/EmployeeController.java
> +    private final EmployeeDAO employeeDAO;
Should have service layer to implement business in real project.

2024-07-08 06:57 UTC, helenhash commented on Week 04/Lecture 08/Assignment 03/src/main/java/com/lecture8/EmployeeCRUD/dao/EmployeeDAO.java
> +    @Transactional(transactionManager = "transactionManager1")
Question: what are case @Transactional does not work fine. Pls explain.

2024-07-16 07:09 UTC, manuellaiv commented on Week 04/Lecture 08/Assignment 03/src/main/java/com/lecture8/EmployeeCRUD/dao/EmployeeDAO.java
> +    @Transactional(transactionManager = "transactionManager1")
I just research it, if a transactional method is called from another method within the same class, the transaction management will not be applied because Spring’s proxy mechanism will not intercept the call. I changed the saveAll method with BatchPreparedStatement🙏

2024-07-20 10:04 UTC, helenhash commented on Week 04/Lecture 08/Assignment 03/src/main/java/com/lecture8/EmployeeCRUD/dao/EmployeeDAO.java
> +    @Transactional(transactionManager = "transactionManager1")
Yes, that's one of the case. Another case is for private method - should notice that.

2024-08-18 08:23 UTC, merged